---
# roles/jails-host/task/jails-supports-ipv4.yml
#
# configure cloned interfaces and ipv4 range of addresses
# TODO: deal with pf or ipfw configuration

- name: check cloned interface
  command: sysrc -c cloned_interfaces={{ jails_clone_interface }}
  register: cloned_if
  ignore_errors: True

- name: setup cloned interface
  command: sysrc cloned_interfaces={{ jails_clone_interface }}
  when: cloned_if|failed

- name: check colone interface range
  command: sysrc -c ifconfig_{{ jails_clone_interface }}_alias0={{ jails_ipv4_range}}
  register: cloned_if_net
  ignore_errors: True

- name: setup clone interface ipv4 range
  command: sysrc ifconfig_{{ jails_clone_interface }}_alias0={{ jails_ipv4_range}}
  when: cloned_if_net|failed

- name: setup clone interface
  command: service netif cloneup
  when: cloned_if_net|failed
