---
# roles/fjails-host/task/mster-templateain.yml
#
# Configure the required zfs filesystems, download the OS files and setup
# The master template for the jails.

- name: create zfs filesystem for jails
  zfs:
    name: "{{ jails_zfs_pool }}{{ jails_dir }}"
    mountpoint: "{{ jails_dir }}"
    state: present

- name: create zfs filesystem for master jail template
  zfs:
    name: "{{ jails_zfs_pool }}{{ jails_dir }}/{{ jail_master_tpl_name }}"
    compression: lz4
    state: present

- name: create directory for downloaded files
  file: 
    name: "{{ jails_dir }}/.downloads"
    state: directory
    mode: 0777
    owner: "{{ remote_user }}"

- name: extract base OS archive
  unarchive:
    src: "{{ local_archive_path }}/base.txz"
    creates: "{{ jails_dir }}/{{ jail_master_tpl_name }}/etc"
    dest: "{{ jails_dir }}/{{ jail_master_tpl_name }}/"

