---
# roles/jails-hosts/task/pf.yml
# configure pf firewall for jails
#

- name: check if pf is enabled
  command: sysrc -c pf_enable="YES"
  ignore_errors: True
  register: pf_enabled

- name: enable pf at boot
  command: sysrc {{ item }}="YES"
  with_items:
    - gateway_enable
    - pf_enable
    - pflog_enable
  when: pf_enabled|failed

- name: deploy pf rules
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0644
  notify: reload pf

- name: enable pf
  shell: "kldload pf.ko; kldload pflog.ko; pfctl -e"
  when: pf_enabled|failed

- name: reload pf
  command: pfctl -f /etc/pf.conf
  when: pf_enabled|failed

