---
# roles/freebsd-host/task/main.yml
#
# Configure a FreeBSD host to deploy jails
#
- name: create zfs filesystem for jails
  zfs:
    name: "{{ zfs_jails_pool }}{{ jails_dir }}"
    mountpoint: "{{ jails_dir }}"
    state: present

- name: create zfs filesystem for master jail template
  zfs:
    name: "{{ zfs_jails_pool }}{{ jails_dir }}/.master"
    compression: lz4
    state: present

- name: create directory for downloaded files
  file: 
    name: "{{ jails_dir }}/.downloads"
    state: directory
    mode: 0777
    owner: "{{ remote_user }}"

- name: get base OS archive
  get_url:
    url: "http://ftp.belnet.be/ftp.freebsd.org/pub/FreeBSD/releases/amd64/{{ jail_version }}-RELEASE/base.txz"
    dest: "{{ zfs_jails_pool }}{{ jails_dir }}/.downloads/{{ jail_version}}-base.txz"
    force: no

- name: extract base OS archive
  unarchive:
    copy: no
    creates: "{{ jails_dir }}/.master/etc"
    dest: "{{ jails_dir }}/.master/"
#
